apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: cert-manager
spec:
  secretName: ingress-certificate-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  duration: 2160h # 90d
  renewBefore: 720h # 30d before SSL will expire, renew it
  commonName: "*.explosion204.space"
  dnsNames:
    - "*.explosion204.space"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "app,kubernetes-dashboard"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "app,kubernetes-dashboard"
